### PR TITLE
open taxonomy list to api

### PR DESCRIPTION
**Pull request by truckydev**
just a little addon.

```python
r = misp.get_taxonomies_list()
print(json.dumps(r, indent=4, sort_keys=True))
```

return taxonomies list

```python
r = misp.get_taxonomy(42)
print(json.dumps(r, indent=4, sort_keys=True))
```
return specific taxonomy

### CODE REVIEW

**Comment by SHSauler** [comment]
((You misspelled `taxonomies`))

**Comment by truckydev** [comment]
Hoooo ...

**Comment by truckydev** [comment]
I corrected the fault and added the possibility of seeing one

**Comment by Rafiot** [comment]
Sorry for the late feedback, can you please update this PR in order to use the new way to do requests: https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L368

**Comment by truckydev** [comment]
done :)

**Comment by Rafiot** [comment]
Are you sure you want to do POST and not GET? Just before, your code was using GET.

**Comment by truckydev** [comment]
I don't know if it's still relevant. I thought you were going to merge pymisp and mymisp-taxonomy.

but for here, you right. 'GET' is adequate ^^

**Comment by Rafiot** [comment]
Merged: https://github.com/MISP/PyMISP/commit/6db31b397a4955f4ce4e586542f7df173aa48c4e

**Pull request closed without merging**
