### PR TITLE
Trustar integration

### PR DESCRIPTION
**Pull request by goodlandsecurity**
Custom integration to scrape Trustar Intel Platform reports and create events in MISP

### CODE REVIEW

**Comment by Rafiot** [comment]
Thank you for the initial work on it! I'll have a look at it asap.

**Comment by Rafiot** [comment]
Looks good!

**Comment by Rafiot** [comment]
I reworked the code: https://github.com/MISP/PyMISP/commit/97d960883c8ad9ecc87c8550beded91a13314872

Note that setting the organization is not needed, and it will be overwritten to the organization of the user (unless your user is admin, and that's a terrible idea to do that, you should *always* use a user in the organization you want to set)

**Comment by goodlandsecurity** [comment]
thank you @Rafiot ! i really appreciate the help/guidance. I am still very new with pymisp, so seeing the changes you made help me to learn how to better utilize it!

**Comment by Rafiot** [comment]
I'm happy to give you as much guidance as possible!

**Pull request merged**
