### PR TITLE
chg: format docstrings in mispevent.py

### PR DESCRIPTION
**Pull request by chrisinmtown**
Add ":param " prefix to parameters to improve ReadTheDocs output.
Fix some minor typos in docstrings.

### CODE REVIEW

**Comment by chrisinmtown** [comment]
I don't seem to be able to add reviewers here.  If I'm missing something obvious, please teach me how.

**Comment by chrisinmtown** [comment]
The Travis builds fail for Python 3.9.

**Comment by chrisinmtown** [comment]
@Rafiot @iglocska please review.

**Comment by chrisinmtown** [comment]
Now that you dropped Python 3.9 @ Travis, how can I re-run the build on this PR?

**Comment by Rafiot** [comment]
Sorry, I was working on something else this week. I'll merge that today.

And just FYI, Python 3.9 fails because there are no compatible lief package yet.

**Comment by Rafiot** [comment]
Thank you very much!

**Comment by chrisinmtown** [comment]
glad to help.

**Pull request merged**
