### PR TITLE
Cache JSON definitions in memory LFU cache provided by cachetools

### PR DESCRIPTION
**Pull request by mback2k**
This is my first attempt to implement the idea discussed in issue #468.

- Path and modified time of JSON file are used as the cache key
- Global state is hidden away inside a root-class for re-use
- Maximum size is 150 considering the number of JSON definitions

During my tests the memory usage of the test suites was halved.

I am looking forward to your feedback!

### CODE REVIEW

**Comment by mback2k** [comment]
I think the CodeFactor issues are not related to the changes of this PR.

**Comment by mback2k** [comment]
Just as a reference point: JSON files are loaded 2981 times during a standalone test suite run.

**Comment by Rafiot** [comment]
Yeah, I started to look at it, and came with a less generic approach than yours, that involved also a bunch of fixes in parts of the code that should ever have been called as often in the first time.

On a big event, we're talking of a load time going from 30+ seconds and 1GB of ram to less than 10s and less than 50MB.

I'll merge both PR.

**Comment by Rafiot** [comment]
Slight note regarding your PR: it adds a dependency, and I'm not totally against it, especially since it adds some safeguards on the amount of files we keep cached (instead of everything forever as long as the script tuns), but I'm going to investigate if there is an alternative without it.

**Comment by mback2k** [comment]
Okay, the approach you went with in https://github.com/MISP/PyMISP/commit/bae942d2ecf9839a37e248c002f43952a83a2a4e is easier and does not require external dependencies. As you mentioned, I see two potential issues with long running Python processes here: 1.) modifications of templates files are not considered, but that may not be a problem at all during normal use and 2.) the number of cached definitions is not limited. Also, your commit just touched AbstractMISP and not PyMISP which also loads the definitions.

**Comment by Rafiot** [comment]
PyMISP loads describe types only once, so it's not much of a problem, but you have a point.

I'll merge the two PR, because mine also solves a bunch of bugs that need to be fixed anyway.

**Comment by mback2k** [comment]
@Rafiot Okay, thanks. Do you want me to rebase this PR to make it easier for you?

**Comment by Rafiot** [comment]
Sure, if you rebase yours on mine, it will be super helpful, but don't rush to do so: I'll not have time to deal with it before Tuesday (Luxembourg time).

**Comment by Rafiot** [comment]
I merged your PR into my branch, I opted for an extra dependency for the remaining python 2.7 people, and lru_cache for the good people using python3 :]

It is mostly similar to yours, but the describeTypes are loaded on the side because they're always required and it is cleaner to do it this way.

Feel free to test the branch and let me know what you think.

**Comment by mback2k** [comment]
@Rafiot Thanks a lot! I planned on doing the rebase this evening, but you were faster than me. ;-)

**Pull request closed without merging**
