### PR TITLE
new: Support brotli compression

### PR DESCRIPTION
**Pull request by JakubOnderka**
To reduce tranfered data and speed up compression and decompressing in compared with gzip.

### CODE REVIEW

**Comment by Rafiot** [comment]
Should I merge this change? I can take care of the mypy complains.

**Comment by Rafiot** [comment]
Bump?

**Comment by JakubOnderka** [comment]
> Should I merge this change? I can take care of the mypy complains.

That would be great!

**Comment by Rafiot** [comment]
done! I added brotli in the deps, just to make things easier.

**Pull request merged**
