### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by jbremer**
Some improvements here and there as I'm using it. Can leave the PR open for a few days until I've finalized some stuff. I'm just going to dump all changes here, as individual PRs for each commit is kind of a hassle.
Please let me know if you some commits need additional work to be acceptable from your side.

### CODE REVIEW

**Comment by Rafiot** [comment]
Oh, nice, I like it :) 

Just let me know when you're good and I'll merge it

**Comment by jbremer** [comment]
@Rafiot, go ahead :-) For now I don't think I'll be modifying anything else. Thanks!

**Comment by Rafiot** [comment]
Thanks! I really like the one_or_more function :)

**Comment by jbremer** [comment]
@Rafiot any clue on when I can expect a new `pymisp` version that will include these commits? :-)

**Comment by Rafiot** [comment]
oh, installable with pip you mean?

**Comment by jbremer** [comment]
Yep, bleeding edge Cuckoo will rely on it ;)

**Comment by Rafiot** [comment]
You confirm it works for you, right? I can tag it now.

**Comment by jbremer** [comment]
Definitely works, tested against your beta instance :)

**Comment by Rafiot** [comment]
excellent, tagging then

**Comment by Rafiot** [comment]
Done!

**Comment by jbremer** [comment]
Thanks, that's great!

**Pull request merged**
