### PR TITLE
MISP Galaxy 2.0 capability create/edit/delete/publish

### PR DESCRIPTION
**Pull request by tomking2**
A bit of a hefty one this one, certainly still a WIP. Would be good to get some input if this is the right approach, and possibly any considerations that must be made before I continue to take this further

This PR brings about more wealth of information through PyMISP when it comes to Galaxies. This includes:
- Galaxy clusters when using `get_galaxy` (with opt. flag `withClusters`)
- Galaxy cluster and elements + relationships with `get_galaxy_cluster`
- Forking existing galaxies with `fork_galaxy_cluster`
- More info on the galaxy when pulling an event (including parsing the 'meta' field as `MISPGalaxyClusterElements`. Possibly we should leave this as is just in case this breaks someone's implementation, thus making it available under cluster_elements and  meta keys)
- Updating the cluster with `update_galaxy_cluster`
- Publishing a galaxy with `publish_galaxy_cluster`
- Adding a relationship to a galaxy cluster with `add_galaxy_cluster_relation`
- Updating a relationship to a galaxy cluster with `update_galaxy_cluster_relation`
- Deleting a relationship to a galaxy cluster with `delete_galaxy_cluster_relation` 

There should probably be more warning handling, e.g.:
- ensuring a user doesn't attempt to make changes to non-default galaxies
- field considerations (no sharing group ID if distribution is not '4'
- other error handling
- more stuff I've certainly forgotten about

Things certainly left to do:
- More function documentation
- Nosetests

Also a quick question - I noticed that none of the classes inherited from MISPAbstract class (e.g. MISPEvent) have no class-level documentation - Is this intentional? Trying to think of a suitable way to help guide people if there were to create a new MISPGalaxyCluster for example - What docs would there be identifying what keys are necessary to create one from scratch? I've done an example on a few of the classes with the `:param` and `:type`, with the use of 'optional' to identify the required fields.

### CODE REVIEW

**Comment by Rafiot** [comment]
I had a short look at the PR, and it looks pretty good to me. I'm not completely fluent in the new galaxy system, but @mokaddem can probably confirm.

From experience, we start discovering issues by the time we have test cases. Are you planning to add some? Otherwise, I can have a look.

**Comment by tomking2** [comment]
Brilliant :). @mokaddem Certainly will identify any risky areas, but I think it should be OK. Still got a few more functions to create, and this is based on my creating/forking/manipulating galaxies and figuring out what functions I'd require.

Don't worry, I'll be adding some test cases once this is ready :), I wouldn't do that to you!

**Comment by Rafiot** [comment]
Thank you! :)

**Comment by tomking2** [comment]
Hey @Rafiot,

Here we go! Should be pretty good to go with a review. Added in tests for galaxy related functionality and the new MISPGalaxy object returned in a MISPEvent.

It is however dependant on a few things:
- PR I submitted on the MISP codebase to better handle REST requests: https://github.com/MISP/MISP/pull/6932
- Code change currently in the develop branch of MISP for hard delete as a posted param for EventReports https://github.com/MISP/MISP/commit/b36f685d88b8c91e6b5879445cb29363b4231157

Not sure how frequently the develop branch of MISP gets merged?

Can always amend the code to remove the 'hard' param change for EventReports from this PR (Acidentally included it in this branch whoops!), however, it's good to keep the hard delete functionality the same across functions.

**Comment by Rafiot** [comment]
It makes sense, keep this PR as it is, I'm figuring out if we merge it for today's release

**Comment by Rafiot** [comment]
I started to look at merging this PR, and the current failures in the github actions are very weird and I ave no idea what is going on. Could you look at it?

**Comment by Rafiot** [comment]
And one more thing: Would you mind rebasing the PR on main?

**Comment by tomking2** [comment]
@Rafiot Ah, yes that could be a problem when there is hundreds of meta. 

I'll look into it today, best case I expect is to keep it as `meta` on a MISP Event, but split into the necessary fields when retrieving/modifying galaxies (MISP needs it split up to be able to update). May create a function to `parse_meta_as_elements` that can be used if people want to split it up

**Comment by Rafiot** [comment]
Thank you!

Maybe something to change on MISP side then. @mokaddem @iglocska: Is there a reason MISP requires the fields in dictionaries on update?

**Comment by tomking2** [comment]
Should all be done (fingers crossed). Side note - Submodules are such a pain!

Still got a few fails - May be a change in the galaxy (different description) and MISP object versions

The only different between the 'meta' and the 'GalaxyClusterElements' is the 'id' of the element, so I can assume it's just to keep the existing ID when updating?

**Comment by Rafiot** [comment]
Yeah, rebasing is a bit of a pain, sorry for that... I generally pop the IDs before comparing, it is often easier.

**Comment by tomking2** [comment]
@Rafiot PRs for MISP have now been merged into the devlop branch; this is probably safe to be merged if you're happy - Not sure the typical time frame for develop -> 2.4 branch.

**Comment by Rafiot** [comment]
develop will be merged in 2.5 just before the next release of MISP, I'll merge your code in a few days.

Thank you for your work!

**Comment by tomking2** [comment]
2.5?! Don't you know it's forever 2.4 ;)

**Comment by Rafiot** [comment]
hahaha yeah, I meant 2.4 ;)

**Comment by tomking2** [comment]
Phew! With this pandemic I need at least one thing to stay constant, and that's MISP@2.4 haha

**Comment by Rafiot** [comment]
okay, I wanted to merge it, but there is still that issue with the meta. Right now, the dump to json is crazy huge and we cannot realistically expect to use it as-is on normal events.

I *think* that exploding the meta should be only done on-demand.

**Comment by tomking2** [comment]
Huh. I thought that one was fixed :thinking:, is this on the dump to JSON from an Event? If so, will look into it and get back to you. If you could point me out the specific test/cmd you're using I can validate it my side to ensure it's kept down

**Comment by Rafiot** [comment]
This test here is where I get the 20x increase: https://github.com/MISP/PyMISP/pull/682/checks?check_run_id=1854407317#step:7:118

**Comment by tomking2** [comment]
I just tested myself, and I don't seem to get a 20x increase, definitely pulled the latest commit?

When I run the only change in the diff is the following (just adding in the default and distribution fields on a galaxy):
```
195d194
<           "default": false,
197d195
<           "distribution": "0",
253d250
<           "default": false,
255d251
<           "distribution": "0",
281d276
<           "default": false,
283d277
<           "distribution": "0",
324d317
<           "default": false,
326d318
<           "distribution": "0",
358d349
<           "default": false,
360d350
<           "distribution": "0",
383d372
<           "default": false,
385d373
<           "distribution": "0",
420d407
<           "default": false,
422d408
<           "distribution": "0",
...... (you get the picture)
```

Just pushed to include these keys in in the JSON export, which should allow it to pass with only a small growth in the file size due to the new keys, and meta isn't being exploded into GalaxyClusters on an event

**Comment by Rafiot** [comment]
... oh, I think you're right.

**Comment by Rafiot** [comment]
Just to keep track if the current issues:
* Bug on MISP side, on delete (only fails when MISP is in debug mode): https://github.com/MISP/MISP/issues/7108

**Comment by Rafiot** [comment]
```
======================================================================
FAIL: test_galaxy_cluster (tests.testlive_comprehensive.TestComprehensive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/raphael/gits/PyMISP/tests/testlive_comprehensive.py", line 2742, in test_galaxy_cluster
    self.assertEqual(new_galaxy_cluster.meta, {'synonyms': ['Test2']})
AssertionError: {} != {'synonyms': ['Test2']}
- {}
+ {'synonyms': ['Test2']}
-------------------- >> begin captured stdout << ---------------------
079e547f-cd92-4669-8939-7b9020feb5bc

--------------------- >> end captured stdout << ----------------------
```

**Comment by Rafiot** [comment]
@tomking2 I think that's the last thing. Do you know what's going on there?

**Comment by Rafiot** [comment]
Okay, ignore what I said, the changes I made and the test suite passes:

```diff
-Subproject commit 27a554ab12acbc1242f801b5682364b2047cf9e0
+Subproject commit e764ed6983bac3a3171fe1a649176224d1abbf0a
diff --git a/pymisp/mispevent.py b/pymisp/mispevent.py
index 20e9856..37d005f 100644
--- a/pymisp/mispevent.py
+++ b/pymisp/mispevent.py
@@ -1242,7 +1242,6 @@ class MISPGalaxyCluster(AbstractMISP):
     def from_dict(self, **kwargs):
         if 'GalaxyCluster' in kwargs:
             kwargs = kwargs['GalaxyCluster']
-
         self.default = kwargs.pop('default', False)
         # If the default field is set, we shouldn't have distribution or sharing group ID set
         if self.default:
diff --git a/tests/testlive_comprehensive.py b/tests/testlive_comprehensive.py
index c35e47b..6f0cf7f 100644
--- a/tests/testlive_comprehensive.py
+++ b/tests/testlive_comprehensive.py
@@ -2739,7 +2739,7 @@ class TestComprehensive(unittest.TestCase):
             self.assertEqual(element.value, "Test2")
 
             # The cluster should have the old meta as a prop
-            self.assertEqual(new_galaxy_cluster.meta, {'synonyms': ['Test2']})
+            self.assertEqual(new_galaxy_cluster.elements_meta, {'synonyms': ['Test2']})
 
             # The cluster element should be updatable
             element.value = "Test3"
@@ -2791,7 +2791,8 @@ class TestComprehensive(unittest.TestCase):
             resp = self.admin_misp_connector.get_galaxy_cluster(new_galaxy_cluster)
             self.assertTrue("errors" in resp)
         finally:
-            self.admin_misp_connector.delete_galaxy_cluster(new_galaxy_cluster)
+            self.admin_misp_connector.delete_galaxy_cluster_relation(relation)
+            self.admin_misp_connector.delete_galaxy_cluster(new_galaxy_cluster, hard=True)
             self.admin_misp_connector.toggle_global_pythonify()
 
     def test_event_galaxy(self):

```

**Comment by tomking2** [comment]
Hey @Rafiot, thanks for looking into this, much appreciated. Yep it's good to go from my view to ahead and merge when you're ready!

**Comment by Rafiot** [comment]
I can do it, no worries. If all goes well, it will be in today's release!

**Pull request merged**
