### PR TITLE
new: [dev] add microblog object tool

### PR DESCRIPTION
**Pull request by VVX7**
Add a microblog object generator.

### CODE REVIEW

**Comment by VVX7** [comment]
I tried fixing the failing codefactor check but my code is still smelly :/

**Comment by Rafiot** [comment]
The code look pretty good, the last two failing things are unimportant, I'll take care of it.

Just one thing before I merge: what is the source of the data you turn into a MISP Object?
I'd like to make clear which type of data it can turn into a MISP Object for for other users of the module.

**Comment by VVX7** [comment]
Using Twitter API status response but not all of the fields are in there (or need to be).  The idea was to keep it generic so we can use Facebook, Reddit, etc in the same object.

That's actually something I've been meaning to ask about.  Do you prefer that I create distinct objects for each social media platform? Like a microblog-twitter, microblog-facebook, and so on.  I'm not sure if it's a great idea considering social media platforms proliferate, but on the other hand we would then have very large objects that contain nuances from each platform (which will get hard to work with especially as the fields are not sorted alphabetically).

I have more objects on the way too so if you let me know what you prefer to see I'll try go that way.

**Comment by Rafiot** [comment]
I'll let it up to you: you're the person using these objects, so depending on what makes sense for you, you can create one single type of object, or multiple.
My approach to create different objects is if I have many (say 10) fields that are only relevant for one source. In that case, it is more confusing than anything else.

Is it possible for you to share the code you use to query the different services? Obviously, not the API keys, but just the code where you use the class in your PR. This way, if someone want to do the same as you, they have an example.
And I am a big fan of default implementations, more than specs, so this way, people won't (badly) re-implement the wheel, and when you receive their data, you can process them immediately.

**Comment by VVX7** [comment]
Sure.  I've built a couple Slack bots to add objects to misp that have some boilerplate for this purpose.  I'll get those online once I clear it with the folks in CTI League. It's GPLv3 anyway.

Bots work like this:
/misp_twitter <misp_event_id> <twitter url or post id>
/misp_builtwith <misp_event_id> <domain or url>

So the bot calls the Twitter API or whatever and then reads the returned data into a MISP object.  It either updates the event if the bot belongs to the same org and otherwise adds an event extension  (after checking if an event extension already exists which it can use).

Pretty useful because manually adding attributes to an object is a real slog.  This boils it down to a one-liner.  

I need to add something to handle tags.   Anyway that's what I'm up to.  Will share when I can.  Working a blog post to document how to build your own.

**Comment by Rafiot** [comment]
That's pretty cool! 

So yeah, when you have a blogpost, or a slack bot boilerplate available, just add a comment in the python code.
And I'll try to add a standalone python script in the example directory, because that's the easiest way to make it available to other users.

**Comment by Rafiot** [comment]
Should I merge the current PR? Or do you have a few more changes to do before?

**Comment by VVX7** [comment]
Nope, nothing else for now. thanks.

**Comment by Rafiot** [comment]
Done, thanks!

**Pull request merged**
