### PR TITLE
Implemented much faster publish method to replace the old one

### PR DESCRIPTION
**Pull request by Deventual**
new publish method that is less resourceful and also having the ability to send emails (same as the web interface).
The method depends on the publish misp api method instead of update.

### CODE REVIEW

**Comment by Rafiot** [comment]
Merged, can you make sure it works for you?

**Comment by Deventual** [comment]
Im pretty sure its working.
I will do some tests in sunday.

**Comment by Rafiot** [comment]
Great, thanks :)

**Comment by Deventual** [comment]
So after some tests it seems to work flawlessly.
Both with string/int as event id or when passing full event instead.

**Pull request merged**
