### PR TITLE
Emailobject tool upgrade

### PR DESCRIPTION
**Pull request by JakubOnderka**
* Support parsing Outlook msg format
* Add IP addresses from `Received` headers
* Add mail headers to email object
* Split real name and e-mail address from `To` and `From` header
* Add e-mail date to object

### CODE REVIEW

**Comment by nighttardis** [comment]
Hey JakubOnderka, I actually have been working on something similar. One thing that has bit me is trying to split the list on commas. If there are comma's in the display name the split will break it at the wrong points. I've been working on a regex that should be more reliable. Also with using the "email.util.parseaddr" function, it is expecting the format to be '"DISPLAY NAME" <EMAIL ADDRESS>' where I've seen and have examples where the display name isn't always in quotes and/or the display name is an email address, both cases seem to mess with parseaddr.

Here's what I'm working on, I haven't had time to fully test but I added two regexes to handle it:
```python
        email_list_regex = r'([^\<]+\s*\<[^\@]+\@[a-z0-9\-]+\.[a-z]{2,}\>|[^\@]+\@[a-z0-9\-]+\.[a-z]{2,})\,?\s*'
        email_list = re.compile(email_list_regex, re.IGNORECASE)
        individual_email_regex = r'\"?([^\<\"]+)\"?\s*\<([^\@]+\@[a-z0-9\-]+\.[a-z]{2,})\>'
        individual_email = re.compile(individual_email_regex, re.IGNORECASE)
```
https://github.com/MISP/PyMISP/compare/main...nighttardis:main

I'm not great with git so not sure I can submit any kind of updates to this pull request, but may be something worth looking into.

**Comment by JakubOnderka** [comment]
@nighttardis I will send complete new version soon, I hope tomorrow. It would be great that after new version will be merged you can test the new implementation or send me samples with different formats to test.

**Comment by JakubOnderka** [comment]
@seamustuohy Can you please test if new implementation can still parse Microsoft eml files?

@nighttardis Can you please test if `To` header parser works as you need?

**Comment by seamustuohy** [comment]
@JakubOnderka I'll take a look at it over the weekend. I must admit, my previous plans for the weekend were to finish up my pull request adding the MSG parsing part of this feature! After the BOM problem I started building a really tiny MSG parser (just header extraction, body, and attachments) using OleFile. But, at least it was a good opportunity to learn about the MS compound file structure! 😝

**Comment by JakubOnderka** [comment]
> @JakubOnderka I'll take a look at it over the weekend. I must admit, my previous plans for the weekend were to finish up my pull request adding the MSG parsing part of this feature! After the BOM problem I started building a really tiny MSG parser (just header extraction, body, and attachments) using OleFile. But, at least it was a good opportunity to learn about the MS compound file structure! 😝

Haha. But maybe still makes sense, my implementation uses mailparser library that just calls `msgconvert` binary written in Perl. So if your implementation is written in Python, it should be better than Perl :D

**Comment by JakubOnderka** [comment]
@Rafiot Do you think we can merge this and test it in the wild?

**Comment by seamustuohy** [comment]
Hey @JakubOnderka. If you don't mind waiting a few days more, I've found a solid library that implements msg parsing in native python and have almost finished incorporating it into your PR.  It reduces the complexity quite a bit, but I still have to do some cleanup and testing to make sure it provides full feature parity. (Sorry for the silence while I worked on it. I just got it to the point where I was sure it would work this morning before work.)

**Comment by JakubOnderka** [comment]
@seamustuohy Of course I can wait. So maybe for my makes sense to remove msg parsing for now, merge just updated version of eml parser and after you finish your library, we will integrate it into `EMailObject` generator. What do you thing about that?

**Comment by seamustuohy** [comment]
Holding briefly so I can integrate the code into this branch would be my preference. But, I am happy to move forward with this in whatever way makes sense to you. If there are external pressures for speed in getting the eml parsing updates included then I can wait until that is done and do a PR against master.  That said, I imagine it would be a bit more work for you to strip out the msg stuff and then for me to re-incorporate it back in on the updated code. As it stands now, it's really just a matter of a few days on my end to get you a PR against this branch. I found a separate library to do the parsing (made by one of the folks at FireEye), finished testing to make sure it is a full replacement, and have just started the integration into your code.

**Comment by Rafiot** [comment]
Sounds great, let's wait, we're not in a rush. Thank you all for the work, it looks neat :)

**Comment by nighttardis** [comment]
@JakubOnderka sorry it took me so long to test, but with the updated code I still get unexpected parsing when the "From" or the "To" is in this format:

To: "[LASTNAME], [FIRSTNAME]" <[EMAIL ADDRESS]>

The code is still creates "to" attributes for each the [LASTNAME] and [FIRSTNAME] and misses the email address completely.

I also ran into a message that got parsed oddly by mailparser and ended up with two "received" dictionaries, and the second one didn't have a "from" key so it errored out. Not sure how common it is, it actually wouldn't be an email I would be parsing with this code anyway, but figured I'd say something. I haven't reviewed the headers completely yet to see if I can see what happened.

**Comment by seamustuohy** [comment]
I've gotten to the point where I can faithfully recreate many parts of an eml file from a msg file with a minimal number of external libraries. At this point one of the challenges is that there is no python library for converting a .msg's RTF version of an eml's HTML text back to HTML. My current thinking is that I should simply include the RTF as an alternative body element instead of increasing the fragility of the library by pulling in more external libraries. I'd be interested in other folks' opinions here.

**Comment by JakubOnderka** [comment]
@nighttardis It works for me:
```
% python3
Python 3.7.4 (default, Jul  9 2019, 18:13:23) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import email.utils
>>> email.utils.parseaddr("\"Onderka, Jakub\" <a@b.cz>")
('Onderka, Jakub', 'a@b.cz')
```

Can you provide code sample that returns incorrect result?

**Comment by nighttardis** [comment]
@JakubOnderka you skipped over line 177 where you are splitting the content of the header on commas. So while the "email.utils.parseaddr" can return correct results the data getting send there would already be incorrect.

`% python3
Python 3.6.9 (default, Jul 17 2020, 12:50:27)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import email.utils
>>> data = "\"Onderka, Jakub\" <a@b.cz>, \"Nighttardis\" <b@a.cz>"
>>> parts = [part.strip() for part in data.split(",")]
>>> print(parts)
['"Onderka', 'Jakub" <a@b.cz>', '"Nighttardis" <b@a.cz>']
>>> for part in parts:
...     print(email.utils.parseaddr(part))
...
('', 'Onderka')
('', 'Jakub')
('Nighttardis', 'b@a.cz')`

**Comment by JakubOnderka** [comment]
@nighttardis Yes, you are right. Fixed now with test.

**Comment by JakubOnderka** [comment]
> I've gotten to the point where I can faithfully recreate many parts of an eml file from a msg file with a minimal number of external libraries. At this point one of the challenges is that there is no python library for converting a .msg's RTF version of an eml's HTML text back to HTML. My current thinking is that I should simply include the RTF as an alternative body element instead of increasing the fragility of the library by pulling in more external libraries. I'd be interested in other folks' opinions here.

My opinion is to integrate msg parser without RTF converter and maybe later we can integrate converter as an optional dependency for people that will need that.

**Comment by Rafiot** [comment]
Sorry for that, I forgot about it. Merging now.

Thanks all for the work!

**Comment by Rafiot** [comment]
So FYI, just installing `libemail-outlook-message-perl` on ubuntu 20.10 isn't enough (it fails silently by creating an empty file, and `msgconvert` discard stderr so you have no way to know what happened).

You need to install `libemail-address-perl` to get that to work.

**Pull request merged**
