### PR TITLE
chg: Support for Payload Delivery > Other attribute as PyMISP function & search_index sharinggroup filter

### PR DESCRIPTION
**Pull request by tomking2**

### CODE REVIEW

**Comment by tomking2** [comment]
Added in new additional feature to filter on the sharinggroup ID on the search_index endpoint.

**Comment by adulau** [comment]
@Rafiot ok for you?

**Comment by Rafiot** [comment]
It it's working for @tomking2, sure ;)

**Comment by tomking2** [comment]
Thanks @Rafiot :) keep up the amazing work

**Pull request merged**
